package util;

public enum DataKey {
    PASSWORD,
    USERNAME,
    CHECKING,
    SAVINGS,
    NEW_ACCOUNT_ID,
    DEFAULT_ACCOUNT_ID,
    AMOUNT,
    API_USERNAME,
    API_PASSWORD,
    TRANSACTION_AMMOUNT;
}
