package util;

public enum DataKey {
    EMAIL,
    PASSWORD,
    USERNAME,
    BANK_USER_PASSWORD,
    CHECKING,
    SAVINGS,
    NEW_ACCOUNT_ID,
    DEFAULT_ACCOUNT_ID,
    AMOUNT,
    API_USERNAME,
    API_PASSWORD,
    CUSTOMER_ID;
}
